@url=https://momagic-backend-asmnt.vercel.app

### GET /products
GET {{url}}/products

### GET /products/:id
GET {{url}}/products/1

### GET /products/category/:category
GET {{url}}/products/category/electronics